{
 "title": "Tech Challange - Fase 3",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(process_num_threads,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Requisições por endpoint - Contact",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((http_requests_received_total{endpoint=~\"api/Contact/.*\"}))",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Requisições por endpoint - Region",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((http_requests_received_total{endpoint=~\"api/Region/.*\"}))",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Latencia Contact",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_sum{endpoint=~\"api/Contact/.*\"}[$__interval]) / rate(http_request_duration_seconds_count{endpoint=~\"api/Contact/.*\"}[$__interval])",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Latencia Region",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_sum{endpoint=~\"api/Region/.*\"}[$__interval]) / rate(http_request_duration_seconds_count{endpoint=~\"api/Region/.*\"}[$__interval])",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Uso de Memoria RAM",
   "type": "histogram",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "dotnet_total_memory_bytes{instance=\"api-region:8080\"}\r\n /1024/1024",
     "legendFormat": "Memoria RAM - Region"
    },
    {
     "expr": "dotnet_total_memory_bytes{instance=\"api-contact:8080\"}\r\n /1024/1024",
     "legendFormat": "Memoria RAM - Contact"
    }
   ]
  },
  {
   "title": "Uso de CPU",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "system_runtime_cpu_usage{instance=\"api-region:8080\"} * 100",
     "legendFormat": "CPU (%) - Region"
    },
    {
     "expr": "system_runtime_cpu_usage{instance=\"api-contact:8080\"} * 100",
     "legendFormat": "CPU (%) - Contact"
    }
   ]
  },
  {
   "title": "Requisições/Status Region",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "targets": [
    {
     "expr": "sum by(http_response_status_code) (\r\n  rate(microsoft_aspnetcore_hosting_http_server_request_duration_count{http_route=~\"api/.*\", instance=\"api-region:8080\"}[5m])\r\n)",
     "legendFormat": "{{http_response_status_code}}"
    }
   ]
  },
  {
   "title": "Requisições/Status Contact",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
   "targets": [
    {
     "expr": "sum by(http_response_status_code) (\r\n  rate(microsoft_aspnetcore_hosting_http_server_request_duration_count{http_route=~\"api/.*\", instance=\"api-contact:8080\"}[5m])\r\n)",
     "legendFormat": "{{http_response_status_code}}"
    }
   ]
  },
  { "title": "Taxa de transmissão de rede", "type": "library-panel-ref", "gridPos": { "h": 8, "w": 12, "x": 0, "y": 55 } }
 ]
}